### PR TITLE
#174: Cast type to TIMESTAMP WITH LOCAL TIME ZONE

### LINKED ISSUE #174: Adapt to Exasol 8: Cast to `TIMESTAMP WITH LOCAL TIME ZONE` where necessary
Adapt this project to Exasol 8.

Currently document based virtual schemas fail when using a mapping with type `TIMESTAMP WITH LOCAL TIME ZONE`. Queries fail with the following error message:

```
Adapter generated invalid pushdown query for virtual table BOOKS: Data type mismatch in column number 1 (1-indexed).Expected TIMESTAMP(3) WITH LOCAL TIME ZONE, but got TIMESTAMP(3). (pushdown query: SELECT "MY_TIMESTAMP" FROM (SELECT "ADAPTER".IMPORT_FROM_FIXED_DATA_ADAPTER("DATA_LOADER", 'rO0ABXNyADhjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5TY2hlbWFNYXBwaW5nUmVxdWVzdOio6FDZAiEzAgACTAAHY29sdW1uc3QAEExqYXZhL3V0aWwvTGlzdDtMABFwYXRoSW5SZW1vdGVUYWJsZXQAQUxjb20vZXhhc29sL2FkYXB0ZXIvZG9jdW1lbnQvZG9jdW1lbnRwYXRoL0RvY3VtZW50UGF0aEV4cHJlc3Npb247eHBzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAXcEAAAAAXNyAERjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5Qcm9wZXJ0eVRvVGltZXN0YW1wQ29sdW1uTWFwcGluZyBuLRd0eJ4vAgACWgAhdXNlVGltZXN0YW1wV2l0aExvY2FsVGltZXpvbmVUeXBlTAAVbm90VGltZXN0YW1wQmVoYXZpb3VydABDTGNvbS9leGFzb2wvYWRhcHRlci9kb2N1bWVudC9lZG1sL0NvbnZlcnRhYmxlTWFwcGluZ0Vycm9yQmVoYXZpb3VyO3hyAENjb20uZXhhc29sLmFkYXB0ZXIuZG9jdW1lbnQubWFwcGluZy5BYnN0cmFjdFByb3BlcnR5VG9Db2x1bW5NYXBwaW5nuNzSJnTCdsoCAAJMABNsb29rdXBGYWlsQmVoYXZpb3VydAA4TGNvbS9leGFzb2wvYWRhcHRlci9kb2N1bWVudC9lZG1sL01hcHBpbmdFcnJvckJlaGF2aW91cjtMABRwYXRoVG9Tb3VyY2VQcm9wZXJ0eXEAfgACeHIAOWNvbS5leGFzb2wuYWRhcHRlci5kb2N1bWVu...) (Session: 1782797395424509952)
```

Currently the relevant test in `DocumentAdapterIT` is skipped on Exasol 8.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #174

### CODE REVIEW

File: src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java [hunk 1]
```diff
@@ -30,38 +28,115 @@ class UdfCallBuilderTest {
...
+                Arguments.of(
+                        PropertyToVarcharColumnMapping.builder().exasolColumnName(colName).varcharColumnSize(5).build(),
+                        "VARCHAR(5)"));
+    }
+
     @Test
     void testBasicSqlBuilding() {
-        final RemoteTableQuery remoteTableQuery = getRemoteTableQueryWithOneColumns();
+        final RemoteTableQuery remoteTableQuery = getRemoteTableQueryWithOneColumn();
+        final FetchQueryPlan queryPlan = new FetchQueryPlan(List.of(), new NoPredicate());
```
Comment (redcatbear) [inline src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java:70]:
```suggestion
        final FetchQueryPlan queryPlan = new FetchQueryPlan(Collections.emptyList(), new NoPredicate());
```

File: src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java [hunk 2]
```diff
@@ -30,38 +28,115 @@ class UdfCallBuilderTest {
...
+        final String udfCallSql = UDF_CALL_BUILDER.getUdfCallSql(queryPlan, remoteTableQuery);
+        assertThat(udfCallSql, matchesRegex(quoteRegex(
+                "SELECT \"TEST_COLUMN\" FROM (SELECT \"ADAPTERS\".IMPORT_FROM_TEST_ADAPTER(\"DATA_LOADER\", '")
+                + "[^']+" + quoteRegex(
+                        "', 'MY_CONNECTION') EMITS (\"TEST_COLUMN\" VARCHAR(123)) FROM (VALUES ) AS \"T\"(\"DATA_LOADER\", \"FRAGMENT_ID\") GROUP BY \"FRAGMENT_ID\") WHERE TRUE")));
```
Comment (redcatbear) [inline src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java:75]: Is this line within the 120 char limit?

File: src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java [hunk 3]
```diff
@@ -30,38 +28,115 @@ class UdfCallBuilderTest {
...
+
     @Test
     void testBasicSqlBuilding() {
-        final RemoteTableQuery remoteTableQuery = getRemoteTableQueryWithOneColumns();
+        final RemoteTableQuery remoteTableQuery = getRemoteTableQueryWithOneColumn();
+        final FetchQueryPlan queryPlan = new FetchQueryPlan(List.of(), new NoPredicate());
+        final String udfCallSql = UDF_CALL_BUILDER.getUdfCallSql(queryPlan, remoteTableQuery);
+        assertThat(udfCallSql, matchesRegex(quoteRegex(
+                "SELECT \"TEST_COLUMN\" FROM (SELECT \"ADAPTERS\".IMPORT_FROM_TEST_ADAPTER(\"DATA_LOADER\", '")
+                + "[^']+" + quoteRegex(
```
Comment (redcatbear) [inline src/test/java/com/exasol/adapter/document/UdfCallBuilderTest.java:74]: This code is quite hard to read. I recommend using line breaks and indentation to make it more clear which parts are quoted and which are raw regex.

File: test-project/mock-project/src/main/java/com/exasol/adapter/document/mock/FixedDataAdapterDialect.java [hunk 4]
```diff
@@ -73,7 +74,16 @@ private static class QueryPlannerStub implements QueryPlanner {
 
         @Override
         public QueryPlan planQuery(final RemoteTableQuery remoteTableQuery, final int maxNumberOfParallelFetchers) {
-            return new FetchQueryPlan(List.of(new StaticDocumentFetcher()), new NoPredicate());
+            final String remoteName = remoteTableQuery.getFromTable().getRemoteName();
+            LOG.info(() -> "Plan query " + remoteTableQuery + " with " + maxNumberOfParallelFetchers
+                    + " max number of parallel fetchers and remote name " + remoteName);
```
Comment (redcatbear) [inline test-project/mock-project/src/main/java/com/exasol/adapter/document/mock/FixedDataAdapterDialect.java:79]:
```suggestion
            LOG.info(() -> "Plan query '" + remoteTableQuery + "' with " + maxNumberOfParallelFetchers
                    + " max number of parallel fetchers and remote name '" + remoteName + "'");
```

File: test-project/mock-project/src/main/java/com/exasol/adapter/document/mock/FixedDataAdapterDialect.java [hunk 5]
```diff
@@ -73,7 +74,16 @@ private static class QueryPlannerStub implements QueryPlanner {
...
+            if (remoteName.equals("EmptyQueryPlan")) {
+                LOG.info("Using empty query plan");
+                return new EmptyQueryPlan();
+            } else {
+                LOG.info(() -> "Using static document fetcher for remote name " + remoteName);
```
Comment (redcatbear) [inline test-project/mock-project/src/main/java/com/exasol/adapter/document/mock/FixedDataAdapterDialect.java:84]:
```suggestion
                LOG.info(() -> "Using static document fetcher for remote name '" + remoteName + "'");
```

**Review by redcatbear — CHANGES_REQUESTED** [review]

**Review by redcatbear — APPROVED** [review]
