### PR TITLE
Refactor/136 remove adapter notes bug comment

### LINKED ISSUE #136: Remove adapterNotes bug comment
Remove comment from SchemaMappingDefinitionToSchemaMetadataConverter.java

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #136

### CODE REVIEW

File: src/main/java/com/exasol/adapter/document/mapping/SchemaMappingToSchemaMetadataConverter.java [hunk 1]
```diff
@@ -89,8 +85,16 @@ public ColumnMetadata convertColumn(final ColumnMapping columnMapping) {
     /**
      * Deserializes a {@link TableMapping} from {@link TableMetadata}.
      *
+     * <p>
+     * We use the adapter notes of the schema here since in the past there was a bug (SPOT-9952) that did not allow use
```
Comment (pj-spoelders) [inline src/main/java/com/exasol/adapter/document/mapping/SchemaMappingToSchemaMetadataConverter.java:89]:
```suggestion
     * We use the adapter notes of the schema here since in the past there was a bug (SPOT-9952) that did not allow us
```

File: src/main/java/com/exasol/adapter/document/mapping/SchemaMappingToSchemaMetadataConverter.java [hunk 2]
```diff
@@ -89,8 +85,16 @@ public ColumnMetadata convertColumn(final ColumnMapping columnMapping) {
...
+     * to store the metadata with the table. However we did not change it now since in the future it might make sense to
+     * move also the Column metadata into the Schema metadata. By that we would have all persistent information in one
+     * place. That makes testing this part a lot easier. Another reason is that it has no downside to do it in that way
```
Comment (pj-spoelders) [inline src/main/java/com/exasol/adapter/document/mapping/SchemaMappingToSchemaMetadataConverter.java:92]:
```suggestion
     * place. That makes testing this part a lot easier. Another reason is that it has no downside to do it that way
```

**Review by pj-spoelders — APPROVED** [review]

**Review by pj-spoelders — APPROVED** [review]
Ok! Looks good!
