### PR TITLE
S3 Virtual Schema for PARQUET files fails if there is more than one table definition in the mapping

### LINKED ISSUE #208: S3 Virtual Schema for PARQUET files fails if there is more than one table definition in the mapping
See the description and investigation results in the correspondent L3 ticket: https://exasol.atlassian.net/browse/L3-3821

Additional Notes by @redcatbear :

* A configuration option that works with inline configuration of the parquet virtual schema does not work when using a mapping file. Both variants should work though.
* In the course of this fix we should also correct the documentation which points at JSON schema EDML 2.1.0 which does not exist (is: 2.0.0).

### PR DESCRIPTION
**Pull request by skyglass**
Closes #208

### CODE REVIEW

File: src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java [hunk 1]
```diff
@@ -67,13 +75,40 @@ private ExasolDocumentMappingLanguageException getParseFailedException(final Str
...
-    /** Make a list of table mappings from the EDML string */
-    private List<TableMapping> parseDefinition(final String edmlString) {
-        final EdmlDefinition edmlDefinition = new EdmlDeserializer().deserialize(edmlString);
-        return new MappingConversionPipeline(this.tableKeyFetcher, this.schemaInferencer).convert(edmlDefinition);
+    /** Make a list of table mappings from the EDML input */
+    private List<TableMapping> validateAndParseDefinition(final EdmlInput edmlInput) {
+        final String edmlString = edmlInput.getEdmlString();
+        try (final StringReader reader = new StringReader(edmlString);
+                final JsonReader jsonReader = Json.createReader(reader)) {
+            final var jsonStructure = jsonReader.read();
```
Comment (antonireus) [inline src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java]: I would avoid `var` in production code, IMO it makes code harder to read for a few chars

File: src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java [hunk 2]
```diff
@@ -67,13 +75,40 @@ private ExasolDocumentMappingLanguageException getParseFailedException(final Str
...
+        }
+    }
+
+    private boolean isArray(JsonStructure jsonStructure) {
+        return jsonStructure.getValueType() == jakarta.json.JsonValue.ValueType.ARRAY;
+    }
+
+    private List<TableMapping> validateAndParseJsonArray(final JsonArray jsonArray) {
+        final List<TableMapping> result = new ArrayList<>();
+        for (final var jsonValue : jsonArray) {
```
Comment (antonireus) [inline src/main/java/com/exasol/adapter/document/mapping/reader/JsonSchemaMappingReader.java]: I would avoid `var` in production code, IMO it makes code harder to read for a few chars

**Review by antonireus — APPROVED** [review]
